# Generated by Django 6.0.7 on 2026-07-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('bike_model', models.CharField(max_length=100)),
                ('complaint', models.TextField()),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
