# Generated by Django 6.0.7 on 2026-07-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garage_name', models.CharField(default='Patel Automobile', max_length=100)),
                ('logo', models.CharField(blank=True, default='/logo.png', max_length=255, null=True)),
                ('address', models.TextField(default='Dandi Main Road, Near National Salt Satyagraha Memorial, Dandi, Navsari, Gujarat - 396430')),
                ('phone', models.CharField(default='+91 98250 12345', max_length=20)),
                ('whatsapp_number', models.CharField(default='+919825012345', max_length=20)),
            ],
        ),
    ]
