# Generated by Django 6.0.7 on 2026-07-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagesettings',
            name='default_labour_charge',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='garagesettings',
            name='default_min_stock',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='garagesettings',
            name='mechanics_list',
            field=models.TextField(default='Vijay Owner, Ramesh Mechanic, Suresh Technician'),
        ),
        migrations.AddField(
            model_name='garagesettings',
            name='timing_text',
            field=models.TextField(default='Mon - Sat: 09:00 AM - 08:30 PM, Sun: 09:00 AM - 02:00 PM'),
        ),
        migrations.AlterField(
            model_name='garagesettings',
            name='address',
            field=models.TextField(default='Near Dandi Pond, Dandi, Valsad, Gujarat - 396385'),
        ),
        migrations.AlterField(
            model_name='garagesettings',
            name='garage_name',
            field=models.CharField(default='Vijay Automobile', max_length=100),
        ),
    ]
