# Generated by Django 6.0.7 on 2026-07-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_garagesettings_default_labour_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagesettings',
            name='email',
            field=models.EmailField(default='contact@vijayautomobile.com', max_length=254),
        ),
    ]
