# Generated by Django 6.0.7 on 2026-07-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_garagesettings_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(default='Admin', max_length=100)),
                ('action_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Admin Patel', max_length=100)),
                ('phone', models.CharField(default='+91 98250 12345', max_length=20)),
                ('email', models.EmailField(default='admin@patelautomobiles.com', max_length=254)),
                ('profile_photo', models.TextField(blank=True, default='/logo.png', null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecycleBinItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('serialized_data', models.TextField()),
                ('deleted_by', models.CharField(default='Admin', max_length=100)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='garagesettings',
            name='email',
            field=models.EmailField(default='contact@patelautomobiles.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='garagesettings',
            name='garage_name',
            field=models.CharField(default='Patel Automobiles', max_length=100),
        ),
        migrations.AlterField(
            model_name='garagesettings',
            name='mechanics_list',
            field=models.TextField(default='Patel Owner, Ramesh Mechanic, Suresh Technician'),
        ),
    ]
