# Generated by Django 6.0.7 on 2026-07-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_adminauditlog_adminprofile_recyclebinitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garagesettings',
            name='logo',
            field=models.TextField(blank=True, default='/logo.png', null=True),
        ),
    ]
