# Generated by Django 6.0.7 on 2026-07-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0006_adminprofile_user_adminprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagesettings',
            name='safety_message',
            field=models.TextField(default='Thank you for choosing us! Wish you a safe & smooth ride. 🛵⛑️'),
        ),
    ]
