# Generated by Django 6.0.7 on 2026-07-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0007_garagesettings_safety_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagesettings',
            name='upi_id',
            field=models.CharField(default='pritpatel9397@oksbi', max_length=100),
        ),
        migrations.AddField(
            model_name='garagesettings',
            name='upi_payee_name',
            field=models.CharField(default='Prit Patel', max_length=100),
        ),
        migrations.AddField(
            model_name='garagesettings',
            name='upi_qr_code',
            field=models.TextField(blank=True, default='/upi_qr.jpg', null=True),
        ),
    ]
