# Generated by Django 6.0.7 on 2026-07-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0008_garagesettings_upi_id_garagesettings_upi_payee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='lockout_tier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
