# Generated by Django 6.0.7 on 2026-07-28 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('bike_model', models.CharField(max_length=100)),
                ('labour_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parts_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='workshop.servicejob')),
            ],
        ),
    ]
