# Generated by Django 6.0.7 on 2026-07-28 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('bike_model', models.CharField(max_length=100)),
                ('assigned_mechanic', models.CharField(default='Unassigned', max_length=100)),
                ('labour_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('parts_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=150)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('STAGED', 'Staged (Temporary)'), ('CONFIRMED', 'Confirmed')], default='STAGED', max_length=15)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='workshop.servicejob')),
            ],
        ),
    ]
