# Generated by Django 6.0.7 on 2026-07-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicejob',
            name='secondary_mechanic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
