# Generated by Django 6.0.7 on 2026-07-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('visit_count', models.IntegerField(default=1)),
                ('last_visit', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
